exercicio_cap4/Models/Home.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace exercicio_cap4.Models
{
    public class Home
    {
        public IQueryable<Tema> Tema;
    }
}

exercicio_cap4/Models/ItemTema.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations; // Adicione esta linha

namespace exercicio_cap4.Models
{
    public class ItemTema
    {
        [Key] // Adicione esta anotação
        public long? ItemTemaId { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public long? TemaId { get; set; }
        public Tema Tema { get; set; }
    }
}

exercicio_cap4/Models/Tema.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace exercicio_cap4.Models
{
    public class Tema
    {

        public long TemaId { get; set; }
        public string Nome { get; set; }
        public string Cor { get; set; }
        public double ValorAluguel { get; set; }
        public virtual ICollection<ItemTema> ItemTemas{ get; set; }

    }
}

exercicio_cap4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using exercicio_cap4.Models;

namespace exercicio_cap4.Controllers
{
    public class HomeController : Controller
    {
        private EFContext context = new EFContext();
        // GET: Home
        public ActionResult Index()
        {
            Home h = new Home();
            h.Tema = context.Temas.OrderBy(c => c.Nome);

            return View(h);
        }
    }
}

exercicio_cap4/Controllers/ItemTemasController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using exercicio_cap4.Services;
using exercicio_cap4.Models;

namespace exercicio_cap4.Controllers
{
    public class ItemTemasController : Controller
    {
        private ItemTemaService itemTemaService = new ItemTemaService();
        private TemaService temaService = new TemaService();

        // GET: ItemTemas
        public ActionResult Index()
        {
            var items = itemTemaService.TodosOsItensTemas();
            return View(items);
        }

        // GET: ItemTemas/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemTema item = itemTemaService.ItemTemaPorID(id);

            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: ItemTemas/Create
        public ActionResult Create()
        {
            ViewBag.Temas = new SelectList(temaService.TodososTemas(), "TemaId", "Nome");
            ViewBag.TemaId = new SelectList(itemTemaService.TodosOsItensTemas().OrderBy(b => b.Nome),
            "TemaId", "Nome");
            return View();
        }

        // POST: ItemTemas/Create
        [HttpPost]
        public ActionResult Create(ItemTema item)
        {
            try
            {
                itemTemaService.AdicionarItemTema(item);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(item);
            }
        }

        // GET: ItemTemas/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemTema item = itemTemaService.ItemTemaPorID(id);

            if (item == null)
            {
                return HttpNotFound();
            }

            ViewBag.TemaId = new SelectList(itemTemaService.TodosOsItensTemas().OrderBy(b => b.Nome), "TemaId", "Nome", item.TemaId);
            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(ItemTema item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    itemTemaService.AtualizarItemTema(item);
                    return RedirectToAction("Index");
                }
                return View(item);
            }
            catch
            {
                return View(item);
            }
        }

        // GET: ItemTemas/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemTema item = itemTemaService.ItemTemaPorID(id);

            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: ItemTemas/Delete/5
        [HttpPost]
        public ActionResult Delete(long id)
        {
            try
            {
                itemTemaService.DeletarItemTema(id);
                TempData["Message"] = "Item foi removido com sucesso!!";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

exercicio_cap4/Controllers/TemasController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using exercicio_cap4.Services;
using exercicio_cap4.Models;

namespace exercicio_cap4.Controllers
{
    public class TemasController : Controller
    {
        private TemaService temaService = new TemaService();

        // GET: Temas
        public ActionResult Index()
        {
            var temas = temaService.TodososTemas();
            return View(temas);
        }

        public ActionResult Create()
        {
            return View();
        }

        // GET: Temas/Edit/1
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tema tema = temaService.TemasporID(id);
            if (tema == null)
            {
                return HttpNotFound();
            }
            return View(tema);
        }

        // GET: Temas/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tema tema = temaService.TemasporID(id);
            if (tema == null)
            {
                return HttpNotFound();
            }
            return View(tema);
        }

        // POST: Temas/Delete/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(long id)
        {
            temaService.DeletarTema(id);
            TempData["Message"] = "Tema foi removido";
            return RedirectToAction("Index");
        }

        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tema tema = temaService.TemasporID(id);
            if (tema == null)
            {
                return HttpNotFound();
            }
            return View(tema);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tema tema)
        {
            if (ModelState.IsValid)
            {
                temaService.AtualizarTema(tema);
                TempData["Message"] = "Tema foi modificado";
                return RedirectToAction("Index");
            }
            return View(tema);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tema tema)
        {
            temaService.AdicionarTema(tema);
            TempData["Message"] = "Tema foi registrado";
            return RedirectToAction("Index");
        }
    }
}

exercicio_cap4/Views/Home/Index.cshtml
@model exercicio_cap4.Models.Home

@{
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
    ViewBag.Title = "Listagem de CATEGORIAS";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <table class="table">
            <tr>
                <th>
                    Temas
                </th>
            </tr>
            <tr>
                @foreach (var item in Model.Tema)
                {

                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>

                }
            </tr>
        </table>
    </div>
</body>
</html>

exercicio_cap4/Views/ItemTemas/Create.cshtml
@model exercicio_cap4.Models.ItemTema
@{
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
    ViewBag.Title = "Registrando um NOVO Item";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
            Registro de um NOVO Item
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Nome, htmlAttributes:
                              new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nome, new
                        {
                            htmlAttributes =
                                  new { @class = "form-control" }
                        })
                        @Html.ValidationMessageFor(model => model.Nome, "",
                                  new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    @Html.LabelFor(model => model.Descricao, htmlAttributes:
                              new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Descricao, new
                        {
                            htmlAttributes =
                                  new { @class = "form-control" }
                        })
                        @Html.ValidationMessageFor(model => model.Descricao, "",
                                  new { @class = "text-danger" })
                    </div>
                </div>




                <div class="form-group">
                    @Html.LabelFor(model => model.TemaId, "TemaId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("TemaId", ViewBag.Temas as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TemaId, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
            <div class="panel-footer panel-info">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Adicionar ItemTema" class="btn btn-success" />
                    @Html.ActionLink("Retornar para a listagem de ItemS", "Index", null,
                    new { @class = "btn btn-warning" })
                </div>
                <br />
                <br />
            </div>
        </div>
    </div>
}
@section ScriptPage {
    <script type="text/javascript">
$(document).ready(function () {
$('li').removeClass("active");
$('#liItemTemas').addClass("active");
});
    </script>
}

exercicio_cap4/Views/ItemTemas/Delete.cshtml
@model exercicio_cap4.Models.ItemTema
@{
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
    ViewBag.Title = "Visualizando detalhes do Item a ser removido";
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Visualizando detalhes do Item a ser removido
    </div>
    <div class="panel-body">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Nome, new
                {
                    htmlAttributes =
                     new { @class = "form-control", disabled = "disabled" }
                })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Descricao)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Descricao, new
                {
                    htmlAttributes =
                     new { @class = "form-control", disabled = "disabled" }
                })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Tema.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Tema.Nome, new
                {
                    htmlAttributes =
                     new { @class = "form-control", disabled = "disabled" }
                })
            </div>
        </div>
    </div>
    <div class="panel-footer panel-info">
        <a href="#" class="btn btn-info" data-toggle="modal"
           data-target="#deleteConfirmationModal">Remover</a>
        @Html.ActionLink("Retornar para a listagem", "Index", null, new { @class = "btn btn-info" })
    </div>
</div>
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">
                    Confirmação de exclusão de Item
                </h4>
            </div>
            <div class="modal-body">
                <p>
                    Você está prestes a remover o item @Model.Nome.ToUpper() do cadastro.
                </p>
                <p>
                    <strong>
                        Você está certo que deseja prosseguir?
                    </strong>
                </p>
                @using (Html.BeginForm("Delete", "ItemTemas", FormMethod.Post,
                new { @id = "delete-form", role = "form" }))
                {
                    @Html.HiddenFor(m => m.ItemTemaId)
                    @Html.AntiForgeryToken()
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" onclick="$('#delete-form').submit();">
                    Sim, exclua este item.
                </button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    Não, não exclua este item.
                </button>
            </div>
        </div>
    </div>
</div>
@section ScriptPage {
    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liItemTemas').addClass("active");
        });
    </script>
}

exercicio_cap4/Views/ItemTemas/Details.cshtml
@model exercicio_cap4.Models.ItemTema
@{
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
    ViewBag.Title = "Visualizando os dados de um Item";
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Visualizando detalhes de um Item
    </div>
    <div class="panel-body">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Nome, new
                {
                    htmlAttributes =
                     new { @class = "form-control", disabled = "disabled" }
                })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Descricao)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Descricao, new
                {
                    htmlAttributes =
                     new { @class = "form-control", disabled = "disabled" }
                })
            </div>
        </div>







        <div class="form-group">
            @Html.LabelFor(model => model.Tema.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Tema.Nome, new
                {
                    htmlAttributes =
                     new { @class = "form-control", disabled = "disabled" }
                })
            </div>
        </div>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Retornar para a listagem", "Index", null,
        new { @class = "btn btn-info" })
    </div>
</div>
@section ScriptPage {
    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liItemTemas').addClass("active");
        });
    </script>
}

exercicio_cap4/Views/ItemTemas/Edit.cshtml
@model exercicio_cap4.Models.ItemTema
@{
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
    ViewBag.Title = "Visualizando os dados de um Item";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
            Alteração dos dados de um Item
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                <h4>ItemTema</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ItemTemaId)
                <div class="form-group">
                    @Html.LabelFor(model => model.Nome, htmlAttributes:
                         new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nome, new
                        {
                            htmlAttributes =
                             new { @class = "form-control" }
                        })
                        @Html.ValidationMessageFor(model => model.Nome, "", new
                        {
                            @class =
                             "text-danger"
                        })
                    </div>
                </div>






                <div class="form-group">
                    @Html.LabelFor(model => model.Descricao, htmlAttributes:
                         new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Descricao, new
                        {
                            htmlAttributes =
                             new { @class = "form-control" }
                        })
                        @Html.ValidationMessageFor(model => model.Descricao, "", new
                        {
                            @class =
                             "text-danger"
                        })
                    </div>
                </div>







                <div class="form-group">
                    @Html.LabelFor(model => model.TemaId, "TemaId", htmlAttributes:
                         new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("TemaId", null, htmlAttributes:
                             new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TemaId, "",
                             new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Gravar alterações" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@section ScriptPage {
    <script type="text/javascript">
$(document).ready(function () {
$('li').removeClass("active");
$('#liItemTemas').addClass("active");
});
    </script>
}

exercicio_cap4/Views/ItemTemas/Index.cshtml
@model IEnumerable<exercicio_cap4.Models.ItemTema>
@{
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
    ViewBag.Title = "Listagem de ItemS";
}
@if (@TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Relação de ItemS registrados
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ItemTemaId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Descricao)
                    </th>
                    <th>Tema</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ItemTemaId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tema.Nome)
                    </td>
                    <td>
                        @Html.ActionLink("Alterar", "Edit", new { id = item.ItemTemaId }) |
                        @Html.ActionLink("Detalhes", "Details", new { id = item.ItemTemaId }) |
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.ItemTemaId })
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Registrar um novo Item", "Create", null,
        new { @class = "btn btn-success" })
    </div>
</div>

@section styles{
    <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")"
          rel="stylesheet">
}
@section ScriptPage {
    <script src=" @Url.Content("~/scripts/DataTables/jquery. dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script type="text/javascript">
$(document).ready(function () {
$('li').removeClass("active");
$('#liItemTemas').addClass("active");
$('.table').dataTable({
"order": [[1, "asc"]]
});
});
    </script>
}

exercicio_cap4/Views/ItemTemas/_PorTema.cshtml
@model IEnumerable<exercicio_cap4.Models.ItemTema>
<div class="panel panel-primary">
    <div class="panel-heading">
        Relação de ItemS registrados para o Tema
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ItemTemaId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>Fabricante</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ItemTemaId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
    </div>
</div>

exercicio_cap4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

exercicio_cap4/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"
          charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/content/bootstrap.css")" rel="stylesheet" />
    @RenderSection("styles", false)
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="page-header bg-danger">
                <h1>
                    Desenvolvimento em ASP.NET MVC
                    <small class="text-danger">
                        Utilizando o Bootstrap
                    </small>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-3 col-md-3 bg-success">
                <ul class="nav nav-pills nav-stacked">
                    <li id="liHome" role="presentation" class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                <li id="liItemTemas" role="presentation">
                        @Html.ActionLink("ItemTemas", "Index","ItemTemas")
                </li>
                <li id="liTemas" role="presentation">
                    @Html.ActionLink("Temas", "Index", "Temas")
                </li>
                </ul>
            </div>
            <div class="col-xs-9 col-md-9">
                <br />
                @RenderBody()
            </div>
        </div> <br />
        <div class="row">
            <div class="col-xs-12 col-md-12 bg-danger">
                <small>Layout com Bootstrap</small>
            </div>
        </div>
    </div>
    <script src="@Url.Content("~/scripts/jquery-2.2.4.js")"></script>
    <script src="@Url.Content("~/scripts/bootstrap.js")"></script>
    @RenderSection("ScriptPage", false);
</body>
</html>

exercicio_cap4/Views/Temas/Create.cshtml
@model exercicio_cap4.Models.Tema

@{
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
    ViewBag.Title = "Registrando um NOVO Tema";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
            Registro de um NOVO Tema
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Nome, htmlAttributes: new
                    {
                        @class = "control-label col-md-2"
                    })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nome, new
                        {
                            htmlAttributes =
                                  new { @class = "form-control" }
                        })
                        @Html.ValidationMessageFor(model => model.Nome, "",
                                  new { @class = "text-danger" })
                    </div>
                </div>




                <div class="form-group">
                    @Html.LabelFor(model => model.Cor, htmlAttributes: new
                    {
                        @class = "control-label col-md-2"
                    })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Cor, new
                        {
                            htmlAttributes =
                                  new { @class = "form-control" }
                        })
                        @Html.ValidationMessageFor(model => model.Cor, "",
                                  new { @class = "text-danger" })
                    </div>
                </div>




                <div class="form-group">
                    @Html.LabelFor(model => model.ValorAluguel, htmlAttributes: new
                    {
                        @class = "control-label col-md-2"
                    })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ValorAluguel, new
                        {
                            htmlAttributes =
                                  new { @class = "form-control" }
                                  //new { @class = "form-control", type="text" }
                        })
                        @Html.ValidationMessageFor(model => model.ValorAluguel, "",
                                  new { @class = "text-danger" })
                    </div>
                </div>



            </div>
        </div>
        <div class="panel-footer panel-info">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar Tema" class="btn btn-success" />
                @Html.ActionLink("Retornar para a listagem de TemaS", "Index", null,
                new { @class = "btn btn-warning" })
            </div>
            <br />
            <br />
        </div>
    </div>
}
@section ScriptPage {
    <script src="~/Scripts/jquery.validate.min.js">
    </script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js">
    </script>
}